
/*2022 Genel Satýþ ve Ödeme Cinsi*/

SELECT TESLIMAT_ID AS 'Teslimat No',
URUNLER.URUN_ADI AS 'Ürün Ýsmi',
ODEME_YONTEMLERI AS 'Ödeme Cinsi',
TESLIMAT_TARIH AS '2022 Genel' 
FROM TESLIMATLAR 
JOIN ODEME_SEKILLERI ON TESLIMATLAR.ODEME_ID = ODEME_SEKILLERI.ODEME_ID
JOIN URUNLER ON TESLIMATLAR.URUN_ID = URUNLER.URUN_ID
WHERE TESLIMAT_TARIH>='2022-04-05'
ORDER BY TESLIMAT_TARIH ASC

/*2022 Mart Satýþ ve Ödeme Cinsi*/

SELECT TESLIMAT_ID AS 'Teslimat No',
URUNLER.URUN_ADI AS 'Ürün Ýsmi',
TESLIMATLAR.ODEME_ID AS 'Ödeme Þekli Kodu',
ODEME_YONTEMLERI AS 'Ödeme Cinsi',
TESLIMAT_TARIH AS '2022 Mart Satýþlarý' 
FROM TESLIMATLAR 
JOIN ODEME_SEKILLERI ON TESLIMATLAR.ODEME_ID = ODEME_SEKILLERI.ODEME_ID
JOIN URUNLER ON TESLIMATLAR.URUN_ID = URUNLER.URUN_ID
WHERE TESLIMAT_TARIH>='2022-03-01' and 
TESLIMAT_TARIH <='2022-03-31'
ORDER BY TESLIMAT_TARIH ASC

/*Hiç Hata Bulunmayan Ürünler*/

SELECT URUN_ADI  AS 'Hata Olmayan Ürünler'
FROM URUNLER
WHERE URUN_ID not in (select URUN_ID from HATALI_URUNLER);

/*Belirli Bir Üründeki Hatalarýn Toplam Satýþýna Oraný*/

SELECT URUN_ADI AS 'Ürün Ýsmi',SUM(HATA_ADET) AS 'Toplam Hata'
,SUM(TESLIMAT_ADET) AS 'Toplam Satýþ'
FROM URUNLER,HATALI_URUNLER,TESLIMATLAR 
WHERE URUNLER.URUN_ID=1 and HATALI_URUNLER.URUN_ID=1 
and TESLIMATLAR.URUN_ID=1
GROUP BY URUNLER.URUN_ADI

/*Tüm Ürünlerin Satýþ Miktarlarý Ve Ürün Gruplarý*/

SELECT TESLIMATLAR.URUN_ID AS 'Ürün Kodu',
URUNLER.URUN_ADI AS 'Ürün Ýsmi',
SUM(TESLIMATLAR.TESLIMAT_ADET) AS 'Satýþ Miktarý',
URUN_GRUPLARI.URUN_GRUP AS 'Ürün Grubu'
FROM TESLIMATLAR
JOIN URUN_GRUPLARI ON TESLIMATLAR.URUN_ID/9+1 = URUN_GRUPLARI.URUN_GRUP_ID
JOIN URUNLER ON URUNLER.URUN_ID=TESLIMATLAR.URUN_ID
GROUP BY TESLIMATLAR.URUN_ID, URUN_GRUPLARI.URUN_GRUP_ID,URUNLER.URUN_ADI,
URUN_GRUPLARI.URUN_GRUP
ORDER BY TESLIMATLAR.URUN_ID ASC

/*2022 Yýlýnda En Çok Satýþ Yapan 10 Ürün*/

SELECT TOP 10 TESLIMATLAR.URUN_ID AS 'Ürün Kodu',
URUNLER.URUN_ADI AS '2022 En Çok Satan Ürün Ýsimleri',
SUM (TESLIMAT_ADET) AS 'Satýþ Miktarý'
FROM TESLIMATLAR
JOIN URUNLER ON TESLIMATLAR.URUN_ID=URUNLER.URUN_ID
WHERE TESLIMATLAR.URUN_ID>=1 AND TESLIMATLAR.URUN_ID<=162
AND TESLIMATLAR.TESLIMAT_TARIH >= '2022-01-01' 
GROUP BY TESLIMATLAR.URUN_ID,URUNLER.URUN_ADI
ORDER BY SUM(TESLIMAT_ADET) DESC

/*2022 Yýlýnda En Az Satýþ Yapan 10 Ürün*/

SELECT TOP 10 TESLIMATLAR.URUN_ID AS 'Ürün Kodu',
URUNLER.URUN_ADI AS '2022 En Az Satan Ürün Ýsimleri',
SUM (TESLIMAT_ADET) AS 'Satýþ Miktarý'
FROM TESLIMATLAR
JOIN URUNLER ON TESLIMATLAR.URUN_ID=URUNLER.URUN_ID
WHERE TESLIMATLAR.URUN_ID>=1 AND TESLIMATLAR.URUN_ID<=162
AND TESLIMATLAR.TESLIMAT_TARIH >= '2022-01-01' 
GROUP BY TESLIMATLAR.URUN_ID,URUNLER.URUN_ADI
ORDER BY SUM(TESLIMAT_ADET) ASC

/*Toplam Yapýlan Teslimatlarýn Satýþ Kanallarý*/

SELECT SATIS_KANALI AS 'Satýþ Kanalý',
COUNT (TESLIMAT_ADET) AS 'Satýþ Miktarý' 
FROM TESLIMATLAR
JOIN SATIS_KANALLARI ON SATIS_KANALLARI.SATIS_KANALI_ID=TESLIMATLAR.SATIS_KANALI_ID
GROUP BY SATIS_KANALI

/*En Çok Ýade Edilen 3 Ürün*/

SELECT TOP 3 URUNLER.URUN_ADI AS 'Ürün Ýsmi',
SUM (IADE_DURUMU_ID) AS 'Ýade Miktarý'
FROM TESLIMATLAR
JOIN URUNLER ON URUNLER.URUN_ID=TESLIMATLAR.URUN_ID
WHERE TESLIMATLAR.URUN_ID>=1 AND TESLIMATLAR.URUN_ID<=162 
GROUP BY TESLIMATLAR.URUN_ID,URUNLER.URUN_ADI 

/*Satýþ Sorumlusu Adeti*/

SELECT COUNT(SATIS_SORUMLU_ID) AS 'Toplam Satýþ Sorumlusu'
FROM SATIS_SORUMLULARI

/*Satýþ Sorumlularý ve Sorumluluklarý*/

SELECT SATIS_SORUMLU_AD AS 'Satýþ Sorumlusu Ýsmi',
SATIS_SORUMLU_SOYAD AS 'Satýþ Sorumlusu Soyisim',
URUN_GRUP AS 'Sorumluluk Alaný'
FROM SATIS_SORUMLULARI
JOIN URUN_GRUPLARI ON SATIS_SORUMLULARI.URUN_GRUP_ID=URUN_GRUPLARI.URUN_GRUP_ID
GROUP BY SATIS_SORUMLULARI.URUN_GRUP_ID,SATIS_SORUMLU_AD,SATIS_SORUMLU_SOYAD,URUN_GRUP


/*Nisan 2022 Ýade Edilen Ürünler*/

SELECT URUN_ADI AS 'Ýade Edilen Ürün',
TESLIMAT_TARIH AS 'Ýade Ayý 2022' 
FROM TESLIMATLAR
JOIN URUNLER ON URUNLER.URUN_ID=TESLIMATLAR.URUN_ID
WHERE TESLIMAT_TARIH>='2022-04-01' AND TESLIMAT_TARIH<='2022-04-30'
AND IADE_DURUMU_ID=1

/*350'den Fazla Satýþ Yapýlan Ürünler Gruplarý Ve Sorumlu Bilgileri*/

SELECT URUNLER.URUN_ADI AS 'ÜrünKodu',
SUM(TESLIMATLAR.TESLIMAT_ADET) AS 'Satýþ Miktarý',
URUN_GRUPLARI.URUN_GRUP AS 'Ürün Grubu', 
SATIS_SORUMLULARI.SATIS_SORUMLU_ID AS 'Satýþ Sorumlusu ID',
SATIS_SORUMLU_AD AS 'Satýþ Sorumlusu Ýsmi',
SATIS_SORUMLU_SOYAD AS 'Satýþ Sorumlusu Soyisim'
FROM TESLIMATLAR
JOIN URUNLER ON URUNLER.URUN_ID=TESLIMATLAR.URUN_ID
JOIN URUN_GRUPLARI ON URUN_GRUPLARI.URUN_GRUP_ID=((TESLIMATLAR.URUN_ID/9)+1)
JOIN SATIS_SORUMLULARI ON SATIS_SORUMLULARI.SATIS_SORUMLU_ID=URUN_GRUPLARI.URUN_GRUP_ID
GROUP BY SATIS_SORUMLULARI.SATIS_SORUMLU_ID,URUNLER.URUN_ADI,URUN_GRUPLARI.URUN_GRUP,
SATIS_SORUMLU_AD,SATIS_SORUMLU_SOYAD
HAVING SUM(TESLIMAT_ADET)>350
ORDER BY 'Satýþ Miktarý' ASC

/*350'den Fazla Kredi Kartý Ýle Satýlmýþ Ürünler*/

SELECT URUNLER.URUN_ADI AS 'Ürün Kodu',
SUM(TESLIMATLAR.TESLIMAT_ADET) AS 'Kredi Kartý Satýþ Miktarý'
FROM TESLIMATLAR
JOIN URUNLER ON URUNLER.URUN_ID=TESLIMATLAR.URUN_ID
WHERE TESLIMATLAR.ODEME_ID=1
GROUP BY URUNLER.URUN_ADI HAVING SUM(TESLIMAT_ADET)>350
ORDER BY 'Kredi Kartý Satýþ Miktarý' ASC

/*350'den Fazla Parakende Satýlmýþ Ürünler*/

SELECT URUNLER.URUN_ADI AS 'Ürün Kodu',
SUM(TESLIMATLAR.TESLIMAT_ADET) AS 'Parekende Satýþ Miktarý'
FROM TESLIMATLAR
JOIN URUNLER ON URUNLER.URUN_ID=TESLIMATLAR.URUN_ID
WHERE TESLIMATLAR.SATIS_KANALI_ID=2
GROUP BY URUNLER.URUN_ADI HAVING SUM(TESLIMAT_ADET)>350
ORDER BY 'Parekende Satýþ Miktarý' ASC




